on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        env:
          JAVA_OPTS: "-Xmx6g -Xms1g"
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
